### ISSUE TITLE
Build with rust 1.54.0

### ISSUE THREAD

**Issue by genofire** [UnifiedPush/gotify-dbus-rust#4]
I am unable to build current master: edb9f37c447a0179a7bb3208eea55ca094bde2b8

```
❯ cargo build
warning: unused import: `r2d2::PooledConnection`
 --> src/lib.rs:2:5
  |
2 | use r2d2::PooledConnection;
  |     ^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

   Compiling unifiedpush_gotify v0.1.0 (~/gotify-dbus-rust)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:1
  |
1 | #![feature(proc_macro_hygiene, decl_macro)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `error`, `trace`, `warn`
  --> src/main.rs:11:11
   |
11 | use log::{error, warn, info, debug, trace};
   |           ^^^^^  ^^^^               ^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `trace`, `warn`
  --> src/registration.rs:14:18
   |
14 | use log::{error, warn, info, debug, trace};
   |                  ^^^^               ^^^^^

warning: unused imports: `error`, `trace`
  --> src/gotify_receiver.rs:13:11
   |
13 | use log::{error, warn, info, debug, trace};
   |           ^^^^^                     ^^^^^

error: aborting due to previous error; 3 warnings emitted

For more information about this error, try `rustc --explain E0554`.
error: could not compile `unifiedpush_gotify`

To learn more, run the command again with --verbose.
```
